import csv
import sys
"""
Summarize the metrics from the result file generated by LogSimEnvironment.

LogSimEnvironment will generate a result file if `result_file` argument is specified.
This script can be used to summarize the overall metrics from the result_file.

With "-b" option, this script also generates a file with the name `result_file + ".bad"`
which contains the scenarios that are considered as bad episodes.

Usage:

    python scripts/summarize_metrics.py <result_file>

    python scripts/summarize_metrics.py -b <result_file>

"""

min_progress_threshold = 0.2
progress_threshold = 2.0


def summarize(result_file: str, generate_bad_result_file=False) -> None:
    """The summary is printed to stdout.

    :param result_file: the result file generated by LogSimEnvironment
    :param generate_bad_result_file: if True, a file with the name `result_file + ".bad"`
        will be generated. This file contains the scenarios that are considered
        as bad episodes.
    """
    num_episodes = 0
    num_safe_episodes = 0
    sum_vals = {}
    sum_vals2 = {}

    if generate_bad_result_file:
        bad_result_file_name = result_file + ".bad"
        bad_result_file = open(bad_result_file_name, mode='w')
    else:
        bad_result_file = None

    with open(result_file, mode='r') as csv_file:
        csv_reader = csv.DictReader(csv_file)
        for k in csv_reader.fieldnames:
            sum_vals[k] = 0
            sum_vals2[k] = 0
        for row in csv_reader:
            for k, v in row.items():
                if k != 'token' and k != 'valid':
                    row[k] = float(v)
            score = row['score']
            if row['no_at_fault_collisions'] or row[
                    'drivable_area_compliance']:
                for k in [
                        'no_at_fault_collisions', 'drivable_area_compliance'
                ]:
                    sum_vals[k] += row[k]
                    sum_vals2[k] += row[k]**2
                
            else:
                for k, v in row.items():
                    if k != 'token' and k != 'valid':
                        sum_vals[k] += row[k]
                        sum_vals2[k] += row[k]**2
                num_safe_episodes += 1
            sum_vals['score'] += score
            sum_vals2['score'] += score**2
            num_episodes += 1
    if generate_bad_result_file:
        bad_result_file.close()
    metric_names = [
        'score', 'no_at_fault_collisions', 'drivable_area_compliance', 
        'ego_progress', 'time_to_collision_within_bound', 
        'comfort',
    ]

    std_vals = {}
    mean_vals = {}
    for k in metric_names:
        n = num_episodes if k in [
            'score', 'no_at_fault_collisions', 'drivable_area_compliance',
        ] else num_safe_episodes
        n = n + 1e-30
        mean_vals[k] = sum_vals[k] / n
        std_vals[k] = (sum_vals2[k] / n - mean_vals[k]**2)**0.5 / n**0.5

    print("num_episodes=%d" % num_episodes)
    print("    ", end='')
    for k in metric_names:
        print('%8s' % k, end=" ")
    print()
    print("mean", end='')
    for k in metric_names:
        print('%8.4g' % mean_vals[k], end=" ")
    print()
    print("std ", end='')
    for k in metric_names:
        print('%8.4g' % std_vals[k], end=" ")
    print()


if __name__ == '__main__':
    if sys.argv[1] == "-b":
        summarize(sys.argv[2], generate_bad_result_file=True)
    else:
        summarize(sys.argv[1])
